[versions]
app-code = "1"
app-version = "1.2.2"
app-packageName = "io.github.vrcmteam.vrcmcs"
agp = "8.13.2"
kotlin = "2.2.20"
compose = "1.8.2"
activity-compose = "1.10.1"
coroutines = "1.10.2"
serialization = "1.8.1"
ktor = "3.2.3"
jna = "5.17.0"
kuromoji = "0.9.0"
wanakana = "1.1.1"
onnxruntime = "1.20.0"
lwjgl = "3.3.6"
whisper-jni = "1.7.1"

[libraries]
whisper-jni = { module = "io.github.givimad:whisper-jni", version.ref = "whisper-jni" }
lwjgl-core = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-openvr = { module = "org.lwjgl:lwjgl-openvr", version.ref = "lwjgl" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
onnxruntime = { module = "com.microsoft.onnxruntime:onnxruntime", version.ref = "onnxruntime" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
jlayer = { module = "javazoom:jlayer", version = "1.0.1" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
kuromoji-ipadic = { module = "com.atilika.kuromoji:kuromoji-ipadic", version.ref = "kuromoji" }
kuromoji-core = { module = "com.atilika.kuromoji:kuromoji-core", version.ref = "kuromoji" }
wanakana-core = { module = "dev.esnault.wanakana:wanakana-core", version.ref = "wanakana" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
