package com.vrcmc.app

enum class AppLanguage(val label: String) { ZH_HANS("\u7b80\u4f53\u4e2d\u6587"), EN("English"), ZH_HANT("\u7e41\u9ad4\u4e2d\u6587"), JA("\u65e5\u672c\u8a9e") }

open class LocaleStrings {
    open val chat = "Chat"; open val devices = "Devices"; open val api = "API"; open val settings = "Settings"; open val done = "Done"; open val theme = "Theme"; open val preferences = "Preferences"
    open val chatbox = "Chatbox"; open val addDevice = "Add device"; open val activeDevice = "Active device"; open val send = "Send"; open val typeMessage = "Type a message..."; open val addIp = "Add a computer IP first"; open val sendFailed = "Send failed"
    open val apiConfiguration = "API configuration"; open val openMenu = "Open menu"; open val selectDevice = "Select device"; open val deleteDevice = "Delete device"; open val deviceAddress = "Receive port:IP:send port"
    open val defaultPortHint = "IP only defaults to 9000:IP:9001"; open val invalidDeviceAddress = "Enter a valid IP and ports"; open val cancel = "Cancel"; open val translationAssistant = "Translation"; open val translating = "Translating..."; open fun translatingRetry(attempt: Int, limit: Int) = "Translating... Retry $attempt/$limit"
    open val deviceManagement = "Device management"; open val editDevice = "Edit device"; open val ipAddress = "IP address"; open val receivePort = "Receive port"; open val sendPort = "Send port"; open val save = "Save"; open val noDevices = "No devices added"
    open val deviceIpHint = "Enter the LAN IP of the device running VRChat."; open val scanNetwork = "Scan local network"; open val scanningNetwork = "Scanning local network..."; open val scanResults = "Devices found"; open val noScanResults = "No devices responded. Check that both devices are on the same local network and try again."; open val unknownDeviceName = "Unknown device"; open val alreadyAdded = "Added"
    open val copyMessage = "Copy"; open val resendMessage = "Send again"
    open val appearance = "Appearance"; open val language = "Language"; open val systemTheme = "System"; open val lightTheme = "Light"; open val darkTheme = "Dark"
    open val configureVrc = "Configure VRC"; open val configureVrcIntro = "Add the generated OSC argument to VRChat's Steam launch options so VRChat can exchange data with this device."
    open val steamStep1 = "Open Steam Library, right-click VRChat, and select Properties."
    open val steamStep2 = "Under General, find Launch Options."
    open val steamStep3 = "Paste the command below into the field, then restart VRChat."
    open val oscLaunchCommand = "OSC launch command"; open val copyCommand = "Copy command"; open val commandCopied = "Copied"; open val refreshIp = "Refresh IP"; open val selectLanIp = "Select this device's LAN IP"
    open val currentLanIp = "This device's LAN IP: %s"; open val lanIpUnavailable = "No usable LAN IPv4 address was found. Connect this device to the same local network as the computer running VRChat, then refresh."
    open val localhostOscNote = "When this app and VRChat run on the same computer, you may use localhost or 127.0.0.1 instead of the detected address."
    open val remoteOscNote = "For another device on your network, the middle value must be that device's IP, for example: --osc=9000:192.168.1.42:9001"
    open val yesterday = "Yesterday"; open val dayBeforeYesterday = "The day before yesterday"
    open val clearHistory = "Clear chat history"; open val clearHistoryTitle = "Clear chat history?"; open val clearHistoryMessage = "All saved messages will be permanently deleted."; open val delete = "Delete"; open val messageTooLong = "Message exceeds the VRChat Chatbox limit (144 characters or 9 lines)"
    open val translationLlm = "Translation & LLM"; open val provider = "Provider"; open val customCompatible = "Custom compatible"; open val apiKey = "API Key (optional for Ollama)"; open val targetLanguage = "Target language"; open val translateBeforeSending = "Translate before sending"; open val testConnection = "Test connection"; open val testing = "Testing..."; open val connectionFailed = "Connection failed; check URL, key and model"; open val connected = "Connected: %s"; open val originalAndTranslationSent = "Original and translation sent"
    open val apiSettingsSubtitle = "Independent provider profiles, protocol-aware requests, and connection diagnostics"
    open val translationService = "Translation service"; open val credentialsAndEndpoint = "Credentials & endpoint"; open val modelAndLanguage = "Model & target language"; open val translationBehavior = "Translation behavior"
    open val apiKeyOptional = "API Key (optional)"; open val showApiKey = "Show API Key"; open val apiKeyRequired = "API Key is required for this provider"
    open val customEndpoint = "Custom endpoint"; open val baseUrlHint = "Enter the endpoint supplied by the provider or relay"; open val officialEndpointLocked = "Official endpoint is locked to prevent accidental changes"
    open val model = "Model"; open val chooseModel = "Choose model"; open val customModelPreserved = "Custom model IDs are preserved exactly as entered"
    open val fallbackModel = "Fallback model"; open val enableFallbackModel = "Use fallback model"; open val fallbackModelHint = "Used only after the primary model exhausts all retryable attempts"; open val fallbackRetryCount = "Fallback retry attempts"; open val fallbackRetryCountHint = "0–10 retries; defaults to 3"
    open val translateBehaviorHint = "Send the original text together with its translation to VRChat"; open val advancedSettings = "Advanced request settings"; open val requestTimeout = "Request timeout"; open val timeoutHint = "3–300 seconds; live chat works best with a short timeout"
    open val retryCount = "Retry attempts"; open val retryCountHint = "0–10 retries when no usable translation is returned"
    open val customHeaders = "Custom request headers"; open val customHeadersHint = "One Name: value header per line. Secrets are hidden with the rest of this provider profile."
    open val streamingResponse = "Streaming response"; open val streamingHint = "Assemble server-sent chunks; useful for compatible relays"
    open val connectionSuccessful = "Connection successful"; open val connectionFailedTitle = "Connection failed"
    open val chooseProvider = "Choose provider"; open val providerPickerHint = "Search a compact list without covering the page"; open val searchProvider = "Search provider or protocol"; open val recommended = "Recommended"
    open val chooseLanguage = "Choose target language"; open val twoLanguageHint = "Choose one or two languages. Two translations run in parallel."
    open val languageSettings = "Translation languages"; open val selectedLanguages = "Target languages"; open val displayOrder = "Display order"; open val effectPreview = "Preview"; open val originalText = "Original"; open val moveUp = "Move up"; open val moveDown = "Move down"
    open val simultaneousInterpretation = "Simultaneous interpretation"; open val enableSimultaneousInterpretation = "Enable simultaneous interpretation"; open val simultaneousInterpretationInputHint = "This feature must be used with your keyboard's voice input function."; open val simultaneousInterpretationHint = "Listen for VRChat MuteSelf at the active device address and send port. Opening the microphone starts live original-text messages; muting or Send performs the normal send flow."; open val listeningPort = "Listening endpoint"; open val listenerReady = "Waiting for VRChat microphone events"; open val listenerStopped = "Listener is off"; open val listenerFailed = "Could not listen on this endpoint: %s"; open val interpreting = "Microphone open"
    open val alwaysInterpretation = "Always interpret"; open val enableAlwaysInterpretation = "Enable always interpret"; open val alwaysInterpretationHint = "Replaces Send with Start. Once started, non-empty text is sent automatically after input has been idle for the configured time."; open val startAlwaysInterpretation = "Start always interpret"; open val stopAlwaysInterpretation = "Stop always interpret"; open val alwaysInterpretationDelay = "Automatic send delay"; open val alwaysInterpretationDelayHint = "Send after this much time without another input event"; open fun seconds(value: String) = "$value seconds"
    open val aboutApp = "About app"; open val version = "Version"; open val errorLogs = "Error logs"; open val noErrorLogs = "No error logs"; open val clearErrorLogs = "Clear error logs"; open val clearErrorLogsMessage = "Delete all saved error logs?"
}
object LocaleStringsEn : LocaleStrings()
object LocaleStringsZhHans : LocaleStrings() {
    override val aboutApp = "关于 APP"; override val version = "版本号"; override val errorLogs = "错误日志"; override val noErrorLogs = "暂无错误日志"; override val clearErrorLogs = "清空错误日志"; override val clearErrorLogsMessage = "确认删除全部错误日志吗？"
    override val deviceManagement = "\u8bbe\u5907\u7ba1\u7406"; override val editDevice = "\u7f16\u8f91\u8bbe\u5907"; override val ipAddress = "IP \u5730\u5740"; override val receivePort = "\u63a5\u6536\u7aef\u53e3"; override val sendPort = "\u53d1\u9001\u7aef\u53e3"; override val save = "\u4fdd\u5b58"; override val noDevices = "\u5c1a\u672a\u6dfb\u52a0\u8bbe\u5907"
    override val deviceIpHint = "\u8bf7\u586b\u5199\u8fd0\u884c VRChat \u7684\u8bbe\u5907\u5728\u5f53\u524d\u5c40\u57df\u7f51\u4e2d\u7684 IP \u5730\u5740\u3002"; override val scanNetwork = "\u626b\u63cf\u5f53\u524d\u5c40\u57df\u7f51"; override val scanningNetwork = "\u6b63\u5728\u626b\u63cf\u5c40\u57df\u7f51..."; override val scanResults = "\u626b\u63cf\u5230\u7684\u8bbe\u5907"; override val noScanResults = "\u672a\u53d1\u73b0\u53ef\u54cd\u5e94\u7684\u8bbe\u5907\u3002\u8bf7\u786e\u8ba4\u4e24\u53f0\u8bbe\u5907\u8fde\u63a5\u540c\u4e00\u5c40\u57df\u7f51\u540e\u91cd\u8bd5\u3002"; override val unknownDeviceName = "\u672a\u77e5\u8bbe\u5907"; override val alreadyAdded = "\u5df2\u6dfb\u52a0"
    override val deviceAddress = "\u63a5\u6536\u7aef\u53e3:IP:\u53d1\u9001\u7aef\u53e3"; override val defaultPortHint = "\u4ec5\u8f93\u5165 IP \u65f6\u9ed8\u8ba4\u4e3a 9000:IP:9001"; override val invalidDeviceAddress = "\u8bf7\u8f93\u5165\u6709\u6548\u7684 IP \u548c\u7aef\u53e3"
    override val yesterday = "\u6628\u5929"; override val dayBeforeYesterday = "\u524d\u5929"
    override val chat = "聊天"; override val devices = "设备"; override val api = "接口"; override val settings = "设置"; override val done = "完成"; override val theme = "主题"; override val preferences = "偏好设置"
    override val chatbox = "Chatbox 消息"; override val addDevice = "添加设备"; override val activeDevice = "当前设备"; override val send = "发送"; override val typeMessage = "输入消息..."; override val addIp = "请先在顶部添加电脑 IP"; override val sendFailed = "发送失败"
    override val apiConfiguration = "API 配置"; override val openMenu = "打开菜单"; override val selectDevice = "选择设备"; override val deleteDevice = "删除设备"
    override val cancel = "取消"; override val translationAssistant = "翻译"; override val translating = "翻译中..."; override fun translatingRetry(attempt: Int, limit: Int) = "翻译中...（重试 $attempt/$limit）"
    override val copyMessage = "复制"; override val resendMessage = "重新发送"
    override val appearance = "外观"; override val language = "语言"; override val systemTheme = "跟随系统"; override val lightTheme = "浅色"; override val darkTheme = "深色"
    override val configureVrc = "配置 VRC"; override val configureVrcIntro = "将自动生成的 OSC 参数填入 VRChat 的 Steam 启动选项，让 VRChat 与此设备交换数据。"
    override val steamStep1 = "打开 Steam 库，右键点击 VRChat，然后选择“属性”。"
    override val steamStep2 = "在“通用”页面中找到“启动选项”。"
    override val steamStep3 = "将下方命令粘贴到输入框，然后重新启动 VRChat。"
    override val oscLaunchCommand = "OSC 启动命令"; override val copyCommand = "复制命令"; override val commandCopied = "已复制"; override val refreshIp = "刷新 IP"; override val selectLanIp = "选择此设备的局域网 IP"
    override val currentLanIp = "此设备的局域网 IP：%s"; override val lanIpUnavailable = "未找到可用的局域网 IPv4 地址。请先让此设备与运行 VRChat 的电脑连接到同一局域网，然后刷新。"
    override val localhostOscNote = "如果本软件与 VRChat 在同一台电脑上运行，也可以使用 localhost 或 127.0.0.1 代替检测到的地址。"
    override val remoteOscNote = "如果要让 VRChat 向网络上的另一台设备发送数据，中间一项必须填写那台设备的 IP，例如：--osc=9000:192.168.1.42:9001"
    override val clearHistory = "清空聊天记录"; override val clearHistoryTitle = "确认清空聊天记录？"; override val clearHistoryMessage = "所有已保存的聊天消息都将被永久删除。"; override val delete = "删除"; override val messageTooLong = "消息超过 VRChat Chatbox 限制（144 字符或 9 行）"
    override val translationLlm = "翻译接口"; override val provider = "服务商"; override val customCompatible = "自定义兼容接口"; override val apiKey = "API Key"; override val targetLanguage = "目标语言"; override val translateBeforeSending = "发送前翻译"; override val testConnection = "测试连接"; override val testing = "测试中..."; override val connectionFailed = "连接失败，请检查 URL、Key 和模型"; override val connected = "连接成功：%s"; override val originalAndTranslationSent = "已发送原文和译文"
    override val apiSettingsSubtitle = "服务商配置独立保存，并根据接口协议发送请求和诊断连接"
    override val translationService = "翻译服务"; override val credentialsAndEndpoint = "凭据与端点"; override val modelAndLanguage = "模型与目标语言"; override val translationBehavior = "翻译行为"
    override val apiKeyOptional = "API Key（可选）"; override val showApiKey = "显示 API Key"; override val apiKeyRequired = "该服务商需要 API Key"
    override val customEndpoint = "自定义端点"; override val baseUrlHint = "填写服务商或中转站提供的接口地址"; override val officialEndpointLocked = "官方端点已锁定，避免意外修改"
    override val model = "模型"; override val chooseModel = "选择模型"; override val customModelPreserved = "自定义模型 ID 将按输入内容原样保存"
    override val fallbackModel = "备用模型"; override val enableFallbackModel = "启用备用模型"; override val fallbackModelHint = "仅在主模型耗尽所有可重试次数后调用"; override val fallbackRetryCount = "备用模型重试次数"; override val fallbackRetryCountHint = "范围 0–10 次，默认 3 次"
    override val translateBehaviorHint = "将原文和译文一起发送至 VRChat"; override val advancedSettings = "高级请求设置"; override val requestTimeout = "请求超时"; override val timeoutHint = "范围 3–300 秒；实时聊天建议使用较短超时"
    override val retryCount = "重试次数"; override val retryCountHint = "未返回可用翻译时重试 0–10 次"
    override val customHeaders = "自定义请求头"; override val customHeadersHint = "每行填写一个 Name: value；内容随当前服务商配置一同保存"
    override val streamingResponse = "流式响应"; override val streamingHint = "拼接服务器推送的数据块，适用于兼容中转接口"
    override val connectionSuccessful = "连接成功"; override val connectionFailedTitle = "连接失败"
    override val chooseProvider = "选择服务商"; override val providerPickerHint = "紧凑显示服务商，可按名称或协议搜索"; override val searchProvider = "搜索服务商或协议"; override val recommended = "推荐"
    override val chooseLanguage = "选择目标语言"; override val twoLanguageHint = "可选择 1–2 种语言；双语翻译会并行执行"
    override val languageSettings = "翻译语言"; override val selectedLanguages = "目标语言"; override val displayOrder = "显示顺序"; override val effectPreview = "效果预览"; override val originalText = "原文"; override val moveUp = "上移"; override val moveDown = "下移"
    override val simultaneousInterpretation = "同声传译"; override val enableSimultaneousInterpretation = "开启同声传译"; override val simultaneousInterpretationInputHint = "此功能需要配合输入法的语音输入功能使用。"; override val simultaneousInterpretationHint = "监听当前设备 IP 和发送端口。游戏内开麦后每次输入都发送一条原文消息，闭麦或点击发送时执行一次正常发送。"; override val listeningPort = "监听端点"; override val listenerReady = "正在等待 VRChat 麦克风事件"; override val listenerStopped = "监听已关闭"; override val listenerFailed = "无法监听此端点：%s"; override val interpreting = "游戏麦克风已打开"
    override val alwaysInterpretation = "始终传译"; override val enableAlwaysInterpretation = "开启始终传译"; override val alwaysInterpretationHint = "发送按钮将替换为开始按钮。开始后，输入框有内容且一段时间没有新的输入事件时自动发送。"; override val startAlwaysInterpretation = "开始始终传译"; override val stopAlwaysInterpretation = "停止始终传译"; override val alwaysInterpretationDelay = "自动发送等待时间"; override val alwaysInterpretationDelayHint = "最后一次输入事件后等待多久自动发送"; override fun seconds(value: String) = "$value 秒"
}
object LocaleStringsZhHant : LocaleStrings() { override val yesterday = "\u6628\u5929"; override val dayBeforeYesterday = "\u524d\u5929"; override val copyMessage = "複製"; override val resendMessage = "重新傳送"; override val languageSettings = "翻譯語言"; override val selectedLanguages = "目標語言"; override val displayOrder = "顯示順序"; override val effectPreview = "效果預覽"; override val originalText = "原文"; override val moveUp = "上移"; override val moveDown = "下移" }
object LocaleStringsJa : LocaleStrings() { override val yesterday = "\u6628\u65e5"; override val dayBeforeYesterday = "\u4e00\u6628\u65e5"; override val copyMessage = "コピー"; override val resendMessage = "再送信"; override val languageSettings = "翻訳言語"; override val selectedLanguages = "翻訳先言語"; override val displayOrder = "表示順序"; override val effectPreview = "プレビュー"; override val originalText = "原文"; override val moveUp = "上へ"; override val moveDown = "下へ" }

fun localeStrings(language: AppLanguage): LocaleStrings = when (language) { AppLanguage.ZH_HANS -> LocaleStringsZhHans; AppLanguage.ZH_HANT -> LocaleStringsZhHant; AppLanguage.JA -> LocaleStringsJa; AppLanguage.EN -> LocaleStringsEn }
